version: "3.8"

services:
  good-indexer:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: node poi-crosschecker.js
    env_file:
      - .env
    environment:
      - GRAPH_NODE=http://host.docker.internal:8030

  wiremock:
    image: wiremock/wiremock
    command:
      - '--enable-browser-proxying=true'
    container_name: wiremock
    volumes:
      - ./src/tests/integration:/home/wiremock/
    ports:
      - 8031:8080

  bad-indexer:
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - wiremock
    command: node poi-crosschecker.js
    env_file:
      - a.env
    environment:
      - GRAPH_NODE=http://host.docker.internal:8031/mock
